spring:
  application:
    name: task-management

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/task_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080